services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=evorun
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d evorun"]
      interval: 5s
      timeout: 5s
      retries: 5

#  backend:
#    # (Aqui virá a configuração do nosso serviço backend no futuro)
#    # build: ./backend
#    # ports:
#    #   - "8000:8000"
#    depends_on:
#      db:
#        condition: service_healthy

volumes:
  postgres_data: